### ISSUE TITLE
[MPI_erweiterung_priority_049]: BPred. Save and load files fully describing models plus a text describing model #45

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/bpred#1]
original ticket: https://github.com/INWT/mpi-bpred/issues/45

- [x] User will be able to save and load files fully describing models plus a text describing the model (text entered by user before saving) for apps ReSources /OsteoBioR /Bpred/ IsoMemo models. The saved files should be loadable directly into R so that a user may execute the models within the R environment (this should include the description of the different functions accessible via help). 
- [x] The user will also be able to load files available from a directory online (for the Desktop version of the apps this will require an internet connection). The files for each app/model will be stored in a separate online directory. These individual directories will be contained within a single directory. In the app interface files stored in an online directory are displayed in a pending list showing their names (without extension). The user selects one of these and presses load to load it.

**Bpred**: most of the above already implemented. However, currently I can save example files within Bpred and this option is no longer necessary. 

- [x] Furthermore, the online files should also be made available in the Desktop version (requires, of course, internet access).

---
- current online directory (inside this repository): https://github.com/Pandora-IsoMemo/bpred/tree/feat/1_loadRemoteModel/inst/app/predefinedModels

**Comment by arunge** [comment]
> **Bpred**: most of the above already implemented. However, currently I can save example files within Bpred and this option is no longer necessary. 

Should it be removed/disabled??

**Comment by isomemo** [comment]
I had reported as a bug that this does not seem to be working in Bpred.

**Comment by arunge** [comment]
Still open here:

> As we discussed missing are data tables and inputs (left side on estimates). With just model results there is not much that can be done in terms of analysis. The same principle should apply to all apps (saving inputs/data with optional saving of results) also as we discussed.

**Comment by arunge** [comment]
I pushed a [new version 22.11.1](https://github.com/Pandora-IsoMemo/bpred/pull/14#issue-1448000149) to the [app](https://isomemoapp.com/app/bpred). With the new version, all inputs are stored when downloading a model and also updated when uploading models (stored with version >= 22.11.1).

@isomemo Please, feel free to test the new version and let me know if all is working as expected now. 

Should we update the _remote model_?

![image](https://user-images.githubusercontent.com/16759098/201892642-a7aaa6ce-17c9-4fd1-9836-39fe54c12941.png)

Will you calculate a new one and store it in the folder: https://github.com/Pandora-IsoMemo/bpred/tree/main/inst/app/predefinedModels ?

**Comment by isomemo** [comment]
@arunge Yes, model saving/loading seems to be working well now! As for the remote model, loading should be done from a directory where I can add/delete models. Please create the directory and let me know its location. Also, please check instructions on this in the specification file.

**Comment by isomemo** [comment]
MapR

**Comment by arunge** [comment]
@isomemo The folder for remote model files is already there: https://github.com/Pandora-IsoMemo/bpred/tree/main/inst/app/predefinedModels

and remote models can be selected here (1):

![image](https://user-images.githubusercontent.com/16759098/206186854-76de8e4c-77ff-4907-85f9-c7b165672a58.png)

However, this app currently has not the option to save only the data and model inputs without the model output. I will add this later if other more important tasks are done. Or should I work on on this feature earlier?

**Comment by arunge** [comment]
If the version number is not updated, new added files will not be available.

**Comment by isomemo** [comment]
@arunge this is not practical! We have many apps and I cannot do this every time files are changed.

It should work as in the specification. The app when loaded will check if there are files in that folder. The folder should be dynamically read.

**Comment by arunge** [comment]
@isomemo Remote models are now directly downloaded from the github page. After adding new models to the folder:
https://github.com/Pandora-IsoMemo/bpred/tree/main/inst/app/predefinedModels you only must restart the app and they should be available.

If there is no internet connection a warning will pop up, and remote models will be taken from the models which were locally saved with the last deployment.

This is currently not the case for the other apps, should I adjust them also? Do you have priorities for this?

**Comment by arunge** [comment]
Regarding:
> This is currently not the case for the other apps, should I adjust them also? Do you have priorities for this?

As discussed, I will add this feature (pointing directly to github folder via url) step by step to the other apps also (but this is not priority).

With [BPred version 23.01.2](https://github.com/Pandora-IsoMemo/bpred/pull/18) the path to the remote models folder was added to the readMe.
