### ISSUE TITLE
Saved files not saving all inputs

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/bpred#13]
@arunge  when loading a saved file this does not include all inputs. Saved file should contain:

- Data inputs in "Data" and "Measures" tabs
- All inputs for tab "Formulas" and any results that may have been generated (under sub-tab "Defined formulas")
- All inputs under tab "Estimates"
-

**Comment by arunge** [comment]
I am fixing this within #1 and closing here.
