### ISSUE TITLE
BPred: Integrate the new module to import data

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/bpred#19]
- [x] integrate the module `importData` from the new package `DataTools`
- [x] remove old code (functions and tests)
- [x] remove not required dependencies

**Comment by arunge** [comment]
Currently there is no button "Import Data" in the Bpred app, but there are 4 places where files can be uploaded:

1.
![image](https://user-images.githubusercontent.com/16759098/215737071-b2ee36d5-06f0-471a-a528-293985c2d32b.png)

2. 
![image](https://user-images.githubusercontent.com/16759098/215737216-850919e2-745e-435c-9dc2-5e650d1e6acc.png)

3.
![image](https://user-images.githubusercontent.com/16759098/215737441-2e05a361-ffe3-4d8f-945b-2b83d172f3c9.png)

4.
![image](https://user-images.githubusercontent.com/16759098/215737594-b0633391-685b-46a0-b7ca-3140958dac63.png)

@isomemo Should at all of the four places the "Browse" option be replaced with the "importData" button?

**Comment by isomemo** [comment]
@arunge Yes, replace all!

**Comment by arunge** [comment]
As decided in our last meeting, I exchanged all `file uploads`.

With [version 23.02.1](https://github.com/Pandora-IsoMemo/bpred/pull/20) of [Bpred-App](https://isomemoapp.com/app/bpred) now online the `file uploads` are exchanged by the `importData` module from the new package `DataTools`.
