### ISSUE TITLE
Bugs and changes

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/bpred#22]
@arunge all issues for Bpred regular version are shown in this video: https://youtu.be/8J1vY5tL0-o

file that I tried to upload: 
[test upload.xlsx](https://github.com/Pandora-IsoMemo/bpred/files/11651279/test.upload.xlsx)

- [x] 1) Measures table not allowing to set a column name. Entered values disappear
- [x] 2) Cannot upload a file with a single column into the Measures table
- [x] 3) Issue with the display of logos
- [x] 4) Change name mpiBpred to Bpred
- [ ] 5) Move Download/Upload to a separate tab
- [x] 6) ~FOR THE DATA IMPORT MODULE: data preview should be optional. Have a check box for this and by default this is not activated. That is no data preview is shown.~ see https://github.com/Pandora-IsoMemo/data-tools/issues/48#issuecomment-1592452048

**Comment by arunge** [comment]
@isomemo With version 23.03.1.4 of BPred main and beta I fixed the [above points](https://github.com/Pandora-IsoMemo/bpred/issues/22#issue-1741432594)  **2., 3., 4.**

**Regarding 1.** The behavior of the shinyMatrix table I cannot change within the app. It would be necessary to changed it directly in the `shinyMatrix` R package which I am not maintaining. Should I ask Andreas to have a look on that?

**Regarding 5.** I need to update the download and upload of models anyway, when I want to apply the updated pandora import module (with the new model upload feature) soon.
I would suggest to touch this part then and to 
- to integrate an "Upload Model" button directly in the tab "Data" at (1):
  ![image](https://github.com/Pandora-IsoMemo/bpred/assets/16759098/23e7c5c6-dd7e-496c-be1e-d37962c472a1)
- to leave the download of models in the "Estimates" tab but put it below the "Estimate Y" button (2)
  ![image](https://github.com/Pandora-IsoMemo/bpred/assets/16759098/79de7a34-f04b-41a4-9e1e-9e68bf72681a)

Would this be ok for you?

**Comment by arunge** [comment]
@isomemo Regarding point 1.
I could fix the issue with the disappearing header entries with the version 23.03.1.5 of BPred [main](https://isomemoapp.com/app/bpred) and [beta](https://isomemoapp.com/app/bpred-beta) and this should already work, now.

There is another issue when tabbing through the cells, the focus gets lost when the matrix is extended automatically. I discussed this with Andreas. He is implementing the [following behavior](https://github.com/INWTlab/shiny-matrix/issues/33#issuecomment-1623088461):

> - Tabbing from outside into matrix: Set focus to the cell at the top-left
> - Tabbing inside the matrix (except last column): Move to the next column
> - Tabbing from the last column: Set focus to the next element on the page
> - Tabbing backwards inside the matrix (except first column): Move to previous column
> - Tabbing backwards from the first column: Set focus on the previous element on the page

I will let you know when this is available online.

**Comment by arunge** [comment]
@isomemo The fix regarding the matrix input is online on BPred [main](https://isomemoapp.com/app/bpred) and [beta](https://isomemoapp.com/app/bpred-beta). Please, note the logic regarding tabbing mentioned [here](https://github.com/Pandora-IsoMemo/bpred/issues/22#issuecomment-1623156904).

What is left is to update the download/upload part of the UI. I will open a separate issue for this.
