### ISSUE TITLE
Update error message

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/bpred#27]
@arunge this error message:

"Independent variables or regression function not found in your formula. Please check formula and specified independent variables and regression functions"

may also be caused by issues in the setting the brackets. Please update the message to read:

"Independent variables or regression function not found in your formula or brackets are missing/misplaced. Please check formula and specified independent variables, regression functions, and brackets."

**Comment by f-lukas** [comment]
@arunge the adjusted error message is now available in the beta app. Should we merge directly into main as this is an uncritical change?

**Comment by arunge** [comment]
@f-lukas yes, you can merge the changes into the main. :+1:

**Comment by arunge** [comment]
@isomemo With [version 23.08.0](https://github.com/Pandora-IsoMemo/bpred/pull/32) on BPred [main](https://isomemoapp.com/app/bpred) and [beta](https://isomemoapp.com/app/bpred-beta) we updated the error message to:

> "Independent variables or regression function not found in your formula. Please review your formula and regression functions to ensure all independent variables are included. Also check for correct placement of brackets or if brackets are missing."
