### ISSUE TITLE
Bug in generating estimates

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/bpred#28]
@mgross @arunge 

1) I loaded this data under the tab "Data": 
[experiment data.xlsx](https://github.com/Pandora-IsoMemo/bpred/files/12012474/experiment.data.xlsx)

2) Defined the relationship as shown below under the tab "Formulas"

![image](https://github.com/Pandora-IsoMemo/bpred/assets/46485054/83275ed3-6500-40d1-a218-15ca5416c4e1)

3) Loaded the file below under the tab "Measures": 
[measures.xlsx](https://github.com/Pandora-IsoMemo/bpred/files/12012961/measures.xlsx)

4) Under the tab "Estimates" defined this relationship (it works): 

Y ~ formula_1((([Atm_13C] - ([Measured_13C] + [Charring_offset] + [Preatrement])) /([Atm_13C] - (([Measured_13C] + [Charring_offset] + [Preatrement])/ 1000))+0)

I then tried this formula: Y ~ formula_1((([Atm_13C] - ([Measured_13C] + [Charring_offset] + [Preatrement])) /([Atm_13C] - (([Measured_13C] + [Charring_offset] + [Preatrement])/ 1000))+ [m] *  ([b] – [a]))

and got the following error:

![image](https://github.com/Pandora-IsoMemo/bpred/assets/46485054/e32e651e-8592-43ce-9f47-922c9f26f62a)

this seems to be related with inputs m,b,a since if I just try this: Y ~ formula_1([m] *  ([b] – [a]))

I again get the error:

![image](https://github.com/Pandora-IsoMemo/bpred/assets/46485054/4c3779a1-5422-4dfa-911f-30aff7dab662)

**Comment by f-lukas** [comment]
@isomemo - It was not so easy to see but there is a dash in the formula between [b] and [a] instead of a minus symbol. That is why the error occurs.

> Y ~ formula_1((([Atm_13C] - ([Measured_13C] + [Charring_offset] + [Preatrement])) /([Atm_13C] - (([Measured_13C] + [Charring_offset] + [Preatrement])/ 1000))+ [m] * ([b] – [a]))

If you replace the dash (–) with a minus (-) and use this formula, it works.

> Y ~ formula_1((([Atm_13C] - ([Measured_13C] + [Charring_offset] + [Preatrement])) /([Atm_13C] - (([Measured_13C] + [Charring_offset] + [Preatrement])/ 1000))+ [m] * ([b] - [a]))

**Comment by arunge** [comment]
@isomemo Can we close here?

**Comment by arunge** [comment]
Closed as just discussed.
