### ISSUE TITLE
Model loading

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/bpred#7]
Not sure if this is supposed to be working... but I load a previously saved model into Bpred nothing changed.

**Comment by arunge** [comment]
belongs to https://github.com/Pandora-IsoMemo/bpred/issues/1

**Comment by arunge** [comment]
@isomemo I could not reproduce the bug. Could you provide the saved model file?

I used the example data from the app, downloaded a model, reloaded the app, and afterwards the upload worked for me:

![image](https://user-images.githubusercontent.com/16759098/175009157-df108e5e-b7b7-41dd-b667-cd10e1242d8a.png)

**Comment by arunge** [comment]
@isomemo Bpred is running again: https://isomemoapp.com/app/bpred, some tests still fail, but we are fixing them.

**Comment by isomemo** [comment]
@arunge Thanks Antonia! Working on my side and managed to load model results. As we discussed missing are data tables and inputs (left side on estimates). With just model results there is not much that can be done in terms of analysis. The same principle should apply to all apps (saving inputs/data with optional saving of results) also as we discussed.

**Comment by arunge** [comment]
> As we discussed missing are data tables and inputs (left side on estimates). With just model results there is not much that can be done in terms of analysis. The same principle should apply to all apps (saving inputs/data with optional saving of results) also as we discussed.

This task belongs to https://github.com/Pandora-IsoMemo/bpred/issues/1. No bug to fix here.
